CREATE SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE EMPLOYEE (
     EID VARCHAR2(5) PRIMARY KEY,
     ENAME VARCHAR2(20) NOT NULL,
     SALARY NUMBER CHECK (SALARY BETWEEN 10000 AND 30000),
     CITY VARCHAR2(20) NOT NULL,
     DOB DATE,
     EXP NUMBER(3)
);

DESC EMPLOYEE;

INSERT ALL
      INTO EMPLOYEE VALUES('E01','AJAY',12000,'KOLKATA','10-JAN-01',3)
      INTO EMPLOYEE VALUES('E02','DHONI',28000,'PUNE','02-MAR-12',7)
      INTO EMPLOYEE VALUES('E03','BISWAJIT',16000,'KOLKATA','18-FEB-23',2)
      INTO EMPLOYEE VALUES('E04','ANIL',25000,'DELHI','14-JUL-93',5)
      INTO EMPLOYEE VALUES('E05','AJAY',10000,'MUMBAI','01-DEC-14',2)
SELECT 1 FROM DUAL;


SELECT * FROM EMPLOYEE;


CREATE TABLE DEPARTMENT (
     DID VARCHAR2(5) PRIMARY KEY,
     DNAME VARCHAR2(20),
     MGRID VARCHAR2(5)
);

DESC DEPARTMENT;

INSERT ALL
      INTO DEPARTMENT VALUES('D1','IT','E02')
      INTO DEPARTMENT VALUES('D2','MARKETING','E04')
      INTO DEPARTMENT VALUES('D3','SALES','E04')
      INTO DEPARTMENT VALUES('D4','ACCOUNT','E02')
SELECT 1 FROM DUAL;

SELECT * FROM DEPARTMENT;


CREATE TABLE PROJECT (
     PID VARCHAR2(5) PRIMARY KEY,
     PNAME VARCHAR2(20),
     PLOCATION VARCHAR2(20),
     DID VARCHAR2(5),
     CONSTRAINT FK_PROJ_DEPT FOREIGN KEY (DID) REFERENCES DEPARTMENT (DID)
);

DESC PROJECT;


INSERT ALL
      INTO PROJECT VALUES('P3','CLOUD','KOLKATA','D1')
      INTO PROJECT VALUES('P2','AZURE','PUNE','D4')
      INTO PROJECT VALUES('P1','DEVOPS','BANGALORE','D3')
SELECT 1 FROM DUAL;

SELECT * FROM PROJECT;

CREATE TABLE WORK (
     EID VARCHAR2(5),
     DID VARCHAR2(5),
     FOREIGN KEY (EID) REFERENCES EMPLOYEE (EID),
     FOREIGN KEY (DID) REFERENCES DEPARTMENT (DID)
);

DESC WORK;


INSERT ALL
      INTO WORK VALUES('E01','D1')
      INTO WORK VALUES('E01','D2')
      INTO WORK VALUES('E01','D3')
      INTO WORK VALUES('E01','D4')
      INTO WORK VALUES('E02','D1')
      INTO WORK VALUES('E02','D4')
      INTO WORK VALUES('E03','D3')
      INTO WORK VALUES('E03','D4')
      INTO WORK VALUES('E05','D2')
      INTO WORK VALUES('E05','D4')
SELECT 1 FROM DUAL;


SELECT * FROM WORK;

-- 1
SELECT ENAME,FLOOR (MONTHS_BETWEEN(SYSDATE,DOB)/12) AS AGE FROM EMPLOYEE;

-- 2
SELECT MAX(SALARY) AS MAX_SALARY FROM EMPLOYEE;

-- 3
SELECT D.DNAME,MAX(E.SALARY) AS MAX_SALARY
FROM EMPLOYEE E
JOIN WORK W ON E.EID=W.EID
JOIN DEPARTMENT D ON W.DID=D.DID
GROUP BY D.DNAME;
